version: '3.9'
services:
  mysql:
    image: mysql/mysql-server:8.0.23
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wp
volumes:
  db_data: {}
  wordpress: {}